### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes-basics#20]
```
molecule-shapes-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672674599309/molecule-shapes-basics/molecule-shapes-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1672674599309%22%2C%22timestamp%22%3A1672677371212%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapesBasics.modelScreen.view.optionsPanel.showBondAnglesCheckbox.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapesBasics.modelScreen.view.optionsPanel.showBondAnglesCheckbox.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672674599309/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:196:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (Sim.ts:922:14)
id: Bayes Puppeteer
Snapshot from 1/2/2023, 8:49:59 AM
```

**Comment by jonathanolson** [comment]
Should be handled above. Closing.
