### ISSUE TITLE
Assertion failure from automated testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes-basics#5]
```
Uncaught Error: Assertion failed: NaN detected in velocity!
Error: Assertion failed: NaN detected in velocity!
    at window.assertions.assertFunction (http://192.168.0.2:8080/assert/js/assert.js:22:13)
    at Array. (http://192.168.0.2:8080/molecule-shapes/js/common/model/PairGroup.js?bust=1433967669292:62:43)
    at Property.inherit._notifyObservers (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967669292:112:29)
    at Property.inherit._setAndNotifyObservers (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967669292:99:14)
    at Property.inherit.set (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967669292:72:16)
    at PairGroup.Object.defineProperty.set [as velocity] (http://192.168.0.2:8080/axon/js/PropertySet.js?bust=1433967669292:136:43)
    at PairGroup.inherit.addVelocity (http://192.168.0.2:8080/molecule-shapes/js/common/model/PairGroup.js?bust=1433967669292:202:23)
    at PairGroup.inherit.repulseFrom (http://192.168.0.2:8080/molecule-shapes/js/common/model/PairGroup.js?bust=1433967669292:187:12)
    at VSEPRMolecule.inherit.update (http://192.168.0.2:8080/molecule-shapes/js/common/model/VSEPRMolecule.js?bust=1433967669292:53:25)
    at ModelMoleculesModel.inherit.step (http://192.168.0.2:8080/molecule-shapes/js/common/model/MoleculeShapesModel.js?bust=1433967669292:37:21)
    at ModelMoleculesModel.inherit.step (http://192.168.0.2:8080/molecule-shapes/js/model/ModelMoleculesModel.js?bust=1433967669292:66:42)
    at animationLoop (http://192.168.0.2:8080/joist/js/Sim.js?bust=1433967669292:729:28)
```

**Comment by phet-steele** [comment]
@jonathanolson, this occurred twice in 10/18 automated testing.

```
Error: Assertion failed: NaN detected in velocity!
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Array. (http://phettest.colorado.edu/molecule-shapes/js/common/model/PairGroup.js?bust=1476808789798:61:19)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1476808789798:139:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1476808789798:167:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1476808789798:155:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1476808789798:123:16)
    at PairGroup.set [as velocity] (http://phettest.colorado.edu/axon/js/PropertySet.js?bust=1476808789798:184:43)
    at PairGroup.addVelocity (http://phettest.colorado.edu/molecule-shapes/js/common/model/PairGroup.js?bust=1476808789798:244:23)
    at PairGroup.repulseFrom (http://phettest.colorado.edu/molecule-shapes/js/common/model/PairGroup.js?bust=1476808789798:219:12)
    at VSEPRMolecule.update (http://phettest.colorado.edu/molecule-shapes/js/common/model/VSEPRMolecule.js?bust=1476808789798:62:25)
```

**Comment by phet-steele** [comment]
Can happen pretty reliably on the first screen. http://phettest.colorado.edu/molecule-shapes-basics/molecule-shapes-basics_en.html?ea&brand=phet&fuzzMouse=100&screens=1

**Comment by jonathanolson** [comment]
Occurring again:
```
molecule-shapes-basics : fuzz : require.js : run
Uncaught Error: Assertion failed: NaN detected in velocity!
Error: Assertion failed: NaN detected in velocity!
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/assert/js/assert.js:21:13)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/molecule-shapes/js/common/model/PairGroup.js?bust=1487041455119:61:19)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/axon/js/Emitter.js?bust=1487041455119:147:49)
    at Property._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/axon/js/Property.js?bust=1487041455119:176:29)
    at Property._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/axon/js/Property.js?bust=1487041455119:165:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/axon/js/Property.js?bust=1487041455119:133:16)
    at PairGroup.set [as velocity] (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/axon/js/PropertySet.js?bust=1487041455119:124:43)
    at PairGroup.addVelocity (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/molecule-shapes/js/common/model/PairGroup.js?bust=1487041455119:244:23)
    at PairGroup.repulseFrom (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/molecule-shapes/js/common/model/PairGroup.js?bust=1487041455119:219:12)
    at VSEPRMolecule.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487041165951/molecule-shapes/js/common/model/VSEPRMolecule.js?bust=1487041455119:62:25)
Approximately 2/13/2017, 8:59:25 PM
```

assigning myself.

**Comment by jonathanolson** [comment]
Automated testing shows no failures since the above commit. Closing.
